### PR TITLE
Added Contact and Occupancy Sensors

### PR DESCRIPTION
**Pull request by jsiegenthaler**
Added ContactSensor and OccupancySensor
Updated config.json and readme respectively
Config remains 100% backwards compatible

### CODE REVIEW

**Comment by nitaybz** [comment]
Hey man, Thanks for all the hard work, it looks great.
I do have one concern though, i'm not quite sure why you went for the approach of having a lot of "disable ..." in the config.
I would want to do this part easier for users so you should have some kind of a drop down with "Sensor Type" options.
First option will be "None" for "no extra sensor", and other options will be motion, occupancy & contact.
Once one of them is chosen you can add your other specific configurations accordingly.

Let me know what you think,
Thanks again

**Comment by jsiegenthaler** [comment]
Hi @nitaybz . The reason was simply that I wanted to maintain 100% config.json backwards compatibility and not deviate too far from your config.schema design.

Another option is, as you say, a different config.schema design with just one dropdown per sensor as you say, and then some code to ensure any existing users with existing configs still work without any errors. It just gets tricky when a new config.schema is opened on an old config..... but I guess with just one motion sensor the impact is minimal.

Let me see - I'll throw something together as a different PR

**Comment by nitaybz** [comment]
I like the second option, I think all backward compatibility issues can be resolved from the code itself, and if you load old config it will just not show those fields and possibly delete them if someone opens the plugin settings and save, so maybe we should have it default for motion sensor so no harm can be done even in this case.

**Comment by jsiegenthaler** [comment]
A single dropdown list limits it to one sensor per switch. Which I guess is fine. Meets my needs... as I need an Occupancy Sensor

**Comment by nitaybz** [comment]
not sure there is a use for a few sensors to trigger all together

**Comment by jsiegenthaler** [comment]
So I reworked the code and created a new PR: https://github.com/nitaybz/homebridge-delay-switch/pull/51
This allows choice of sensor type and mode, but only one sensor per delay switch.

**Pull request closed without merging**
