### PR TITLE
make motion sensor active duration configurable

### PR DESCRIPTION
**Pull request by jyy**

### CODE REVIEW

**Comment by jyy** [comment]
just making the motion sensor duration configurable instead of the previously hardcoded 3000ms.  If I enable notifications for the motion sensor, I am getting multiple "motion detected" push notifications and my hypothesis is that this might not happen if I decrease the motion timeout.

**Comment by jyy** [comment]
My hypothesis was incorrect.  Just tested locally and it didn’t change the multiple motion notifications.

edit: i was doing more testing and actually increased the motion sensor active duration to 30 seconds and it solved my issue.  re-opening PR

**Comment by jyy** [comment]
@nitaybz any thoughts?

**Comment by nitaybz** [comment]
are you getting multiple notifications at the same time?

**Comment by jyy** [comment]
@nitaybz so before I made any modifications, yes, the motion sensor would send multiple notifications.  my first thought was that I should shorten the duration of the motion sensor but this still resulted in multiple notifications.  when i lengthened the timeout to something like 30 seconds, I would only receive one motion notification.

**Comment by nitaybz** [comment]
this is weird behaviour... I'll investigate it... can you share your config for this accessor?

**Comment by jyy** [comment]
Sure, it’s just set to 30000.

I’ve tried with both the default 3000 and 1000; both of those gave me multiple notifications.

**Comment by nitaybz** [comment]
can you share your homebridge config? and maybe automations in home app?

**Comment by jyy** [comment]
I don’t have my Homebridge confit accessible now.  Will post later. 

Automation is:
turn on delay switch when garage door opens.

**Comment by jyy** [comment]
```        
    {
            "accessory": "DelaySwitch",
            "name": "GarageDelaySwitch",
            "disableSensor": false,
            "delay": 3000,
            "sensorActiveDuration": 30000
    } 
```

**Comment by nitaybz** [comment]
I activated notifications for 3 of my delay sensors and never got duplicate notifications... I'm afraid this issue is at your side only... it also doesn't make sense that increasing the "triggered" state time will avoid the notification as the notification is being sent when the motion sensor is triggered and not when it's off... please make sure you don't have any duplicates in automations or any other weird thing that can interfere here.. maybe duplicates in config?

**Comment by jyy** [comment]
There are no duplicates.  Consider the case that maybe my garage opener is reporting the open state multiple times over a time period greater than 3 seconds?

**Comment by nitaybz** [comment]
what would be the best scenario for you?
to stop getting notifications for the time when the motion sensor is active? 3 seconds, or keeping the motion sensor active as long as it keeps getting commands that timer is off? this will make sure you only getting the notification the first time and leave it on until no new timers have been set (in the past 3 seconds on your case)

**Comment by nitaybz** [comment]
can you try to install a version I made from a different branch?
`sudo npm install -g https://github.com/nitaybz/homebridge-delay-switch#motionfix`

**Comment by jyy** [comment]
yes, but i've just arrived at work  so will be in about 8 hours from now

**Comment by nitaybz** [comment]
ok... let me know...

**Comment by jyy** [comment]
so far looks good when triggering the delay switch manually.  will let you know if it behaves any differently through the automation.

**Comment by jyy** [comment]
Spoke too soon, just received two motion alerts together.  I agree with you that this behavior seems to be something with my setup.  Since the lengthening of the motion duration is a workaround for my use case maybe it’s easiest to just merge my change?  After all, the config is optional and defaults to the value you originally had hard-coded.

**Comment by jyy** [comment]
closing; the usefulness of the motion sensor tied to my garage door opening/closing is minimal.

**Pull request closed without merging**
